# data process config
data_cfgs:
  ontonotes: cfgs/data_cfgs/ontonotes5.yml
  conll: cfgs/data_cfgs/conll2003.yml

# annotation config
anno_cfgs:
  raw:  # LLM classify the given entities, 2-stage pipeline
    - cfgs/2_stage/anno_cfg_0.yml
    - cfgs/2_stage/anno_cfg_simp.yml
    - cfgs/2_stage/anno_cfg.yml
#    - cfgs/2_stage/anno_cfg_20.yml
#    - cfgs/2_stage/anno_cfg_gd_20.yml
#    - cfgs/2_stage/anno_cfg_gd_20_simp.yml
  single_type:  # LLM recognize entities given single type
    - cfgs/single_type/anno_cfg_st_simp.yml  # w/o analysis
    - cfgs/single_type/anno_cfg_st_gd_20.yml  # w/o analysis
    - cfgs/single_type/anno_cfg_st_20.yml  # w/o analysis
    - cfgs/single_type/anno_cfg_st.yml  # w/o analysis
    - cfgs/single_type/anno_cfg_st_an.yml  # w analysis
    - cfgs/single_type/anno_cfg_st_20_an.yml  # w analysis
  raw_few_shot:  # LLM classify the given entities, 2-stage pipeline, few-shot setting
    - cfgs/2_stage/anno_cfg_fs_1_simp.yml  # 1-shot setting
    - cfgs/2_stage/anno_cfg_fs_1.yml  # 1-shot setting
    - cfgs/2_stage/anno_cfg_fs_5.yml  # 5-shot setting

  st_few_shot:  # LLM recognize entities given single type, few-shot setting
    - cfgs/single_type/anno_cfg_st_fs_5.yml
    - cfgs/single_type/anno_cfg_st_fs_1.yml
    - cfgs/single_type/anno_cfg_st_fs_1_simp.yml
  mt_few_shot:  # multi-type prompt, few-shot setting
    - cfgs/multi_type/anno_cfg_mt_fs_5.yml
    - cfgs/multi_type/anno_cfg_mt_fs_1.yml
    - cfgs/multi_type/anno_cfg_mt_fs_0.yml
  cand_mention_fs:  # candidate mention, few-shot setting
    - cfgs/cand_mention/anno_cfg_cm_fs_0.yml
    - cfgs/cand_mention/anno_cfg_cm_fs_1.yml
    - cfgs/cand_mention/anno_cfg_cm_fs_5.yml
  sb_fs:  # subset type prompt, few-shot setting
    - cfgs/subset_type/anno_cfg_sb_fs_0.yml
    - cfgs/subset_type/anno_cfg_sb_fs_1.yml
    - cfgs/subset_type/anno_cfg_sb_fs_5.yml
  sc_fs:  # subset candidate prompt, few-shot setting
    - cfgs/subset_cand/anno_cfg_sc_fs_5.yml
    - cfgs/subset_cand/anno_cfg_sc_fs_1.yml

# api config
api_cfg: cfgs/api.yml

# labels config
labels_cfg: cfgs/labels.yml
